site_name: SWJTUNSA-Wiki
repo_url: https://github.com/k1ndr3dru4n/SWJTUNSA-Wiki
repo_name: SWJTUNSA-Wiki
use_directory_urls: true

theme:
  logo: assets/img/logo.png
  favicon: assets/img/logo remake.png
  name: material
  language: zh
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: orange
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black 
      accent: green
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式

plugins:
  - search

nav:
  - 主页:
    - 简介: home/intro.md
  - 关于网安协会:
    - 组成:
      - 部门: organize/departments.md
      - 群聊: organize/groups.md
    - 活动:
      - 线下培训: activities/training.md
      - CTF新秀杯: activities/rookie.md
      - 网络安全宣传周: activities/week.md
    - 荣誉: glory/glory.md
  - 关于CTF:
    - 简介: CTF/intro.md
    - Misc: CTF/misc.md
    - Web: CTF/web.md
    - Crypto: CTF/crypto.md
    - Reverse: CTF/reverse.md
    - Pwn: CTF/pwn.md
    - AI: CTF/ai.md
    - Mobile: CTF/mobile.md
    - OSINT: CTF/osint.md
  - 资料: 
    - SWJTU-CTF平台: resources/swjtu-ctf.md
    - 相关链接: resources/links.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
